export enum AddressState {
  "AL" = "AL",
  "AK" = "AK",
  "AZ" = "AZ",
  "AR" = "AR",
  "CA" = "CA",
  "CO" = "CO",
  "CT" = "CT",
  "DE" = "DE",
  "DC" = "DC",
  "FL" = "FL",
  "GA" = "GA",
  "HI" = "HI",
  "ID" = "ID",
  "IL" = "IL",
  "IN" = "IN",
  "IA" = "IA",
  "KS" = "KS",
  "KY" = "KY",
  "LA" = "LA",
  "ME" = "ME",
  "MD" = "MD",
  "MA" = "MA",
  "MI" = "MI",
  "MN" = "MN",
  "MS" = "MS",
  "MO" = "MO",
  "MT" = "MT",
  "NE" = "NE",
  "NV" = "NV",
  "NH" = "NH",
  "NJ" = "NJ",
  "NM" = "NM",
  "NY" = "NY",
  "NC" = "NC",
  "ND" = "ND",
  "OH" = "OH",
  "OK" = "OK",
  "OR" = "OR",
  "PA" = "PA",
  "RI" = "RI",
  "SC" = "SC",
  "SD" = "SD",
  "TN" = "TN",
  "TX" = "TX",
  "UT" = "UT",
  "VT" = "VT",
  "VA" = "VA",
  "WA" = "WA",
  "WV" = "WV",
  "WI" = "WI",
  "WY" = "WY",
}

export const addressStateToName: Record<AddressState, string> = {
  [AddressState.AL]: "Alabama",
  [AddressState.AK]: "Alaska",
  [AddressState.AZ]: "Arizona",
  [AddressState.AR]: "Arkansas",
  [AddressState.CA]: "California",
  [AddressState.CO]: "Colorado",
  [AddressState.CT]: "Connecticut",
  [AddressState.DE]: "Delaware",
  [AddressState.DC]: "District of Columbia",
  [AddressState.FL]: "Florida",
  [AddressState.GA]: "Georgia",
  [AddressState.HI]: "Hawaii",
  [AddressState.ID]: "Idaho",
  [AddressState.IL]: "Illinois",
  [AddressState.IN]: "Indiana",
  [AddressState.IA]: "Iowa",
  [AddressState.KS]: "Kansas",
  [AddressState.KY]: "Kentucky",
  [AddressState.LA]: "Louisiana",
  [AddressState.ME]: "Maine",
  [AddressState.MD]: "Maryland",
  [AddressState.MA]: "Massachusetts",
  [AddressState.MI]: "Michigan",
  [AddressState.MN]: "Minnesota",
  [AddressState.MS]: "Mississippi",
  [AddressState.MO]: "Missouri",
  [AddressState.MT]: "Montana",
  [AddressState.NE]: "Nebraska",
  [AddressState.NV]: "Nevada",
  [AddressState.NH]: "New Hampshire",
  [AddressState.NJ]: "New Jersey",
  [AddressState.NM]: "New Mexico",
  [AddressState.NY]: "New York",
  [AddressState.NC]: "North Carolina",
  [AddressState.ND]: "North Dakota",
  [AddressState.OH]: "Ohio",
  [AddressState.OK]: "Oklahoma",
  [AddressState.OR]: "Oregon",
  [AddressState.PA]: "Pennsylvania",
  [AddressState.RI]: "Rhode Island",
  [AddressState.SC]: "South Carolina",
  [AddressState.SD]: "South Dakota",
  [AddressState.TN]: "Tennessee",
  [AddressState.TX]: "Texas",
  [AddressState.UT]: "Utah",
  [AddressState.VT]: "Vermont",
  [AddressState.VA]: "Virginia",
  [AddressState.WA]: "Washington",
  [AddressState.WV]: "West Virginia",
  [AddressState.WI]: "Wisconsin",
  [AddressState.WY]: "Wyoming",
};
