export enum DisclosingEntity {
  "SoleProprietorship" = "SoleProprietorship",
}

export enum AddressState {
  "AL" = "AL",
  "AK" = "AK",
  "AZ" = "AZ",
  "AR" = "AR",
  "CA" = "CA",
  "CO" = "CO",
  "CT" = "CT",
  "DE" = "DE",
  "DC" = "DC",
  "FL" = "FL",
  "GA" = "GA",
  "HI" = "HI",
  "ID" = "ID",
  "IL" = "IL",
  "IN" = "IN",
  "IA" = "IA",
  "KS" = "KS",
  "KY" = "KY",
  "LA" = "LA",
  "ME" = "ME",
  "MD" = "MD",
  "MA" = "MA",
  "MI" = "MI",
  "MN" = "MN",
  "MS" = "MS",
  "MO" = "MO",
  "MT" = "MT",
  "NE" = "NE",
  "NV" = "NV",
  "NH" = "NH",
  "NJ" = "NJ",
  "NM" = "NM",
  "NY" = "NY",
  "NC" = "NC",
  "ND" = "ND",
  "OH" = "OH",
  "OK" = "OK",
  "OR" = "OR",
  "PA" = "PA",
  "RI" = "RI",
  "SC" = "SC",
  "SD" = "SD",
  "TN" = "TN",
  "TX" = "TX",
  "UT" = "UT",
  "VT" = "VT",
  "VA" = "VA",
  "WA" = "WA",
  "WV" = "WV",
  "WI" = "WI",
  "WY" = "WY",
}

export enum StateApprovedTraining {
  "CHS" = "Children's Home Society of NJ (Trenton)",
  "CF" = "Children's Futures (Trenton)",
  "STS" = "Sister to Sister Community Doulas of Essex County (Newark)",
  "NJDLC" = "New Jersey Doula Learning Collaborative (NJDLC)",
  "PMCH" = "The Partnership for Maternal and Child Health of Northern New Jersey (Paterson, Newark)",
  "NONE" = "None of these",
}
