#!/usr/bin/env bash

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

if ! npm run prettier:check ; then
    echo "Run \`npm run prettier\` to fix";
    exit 1;
fi

npm run lint
npm run typecheck