name: end-to-end-tests

on:
  workflow_call:
    inputs:
      env_test_file:
        required: true
        type: string
      cypress_run_command:
        required: true
        type: string

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm ci
      - name: Use ${{ inputs.env_test_file }}
        if: ${{ inputs.env_test_file != '.env.test' }}
        run: mv ${{ inputs.env_test_file }} .env.test
      - name: Build the application
        run: NODE_ENV=test npm run build
      - name: Start the application
        run:
          NODE_ENV=test npm start & npx wait-on
          http://localhost:3000/humanservices/dmahs/info/doulahelp
      - name: Run cypress tests
        run: npm run "${{ inputs.cypress_run_command }}"
