name: end-to-end-tests-single-suite

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      env_test_file:
        required: true
        type: string
      cypress_run_command:
        required: true
        type: string
      use_dev_server:
        required: false
        type: boolean

jobs:
  end-to-end-tests-single-suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "24"
      - name: Install dependencies
        run: npm ci
      - name: Use ${{ inputs.env_test_file }}
        if: ${{ inputs.env_test_file != '.env.test' }}
        run: mv ${{ inputs.env_test_file }} .env.test
      - name: Build and start the production application
        if: ${{ !inputs.use_dev_server }}
        run:
          (npm run build -- --mode test && npm run preview -- --mode test) & npx wait-on
          http://localhost:3000/humanservices/dmahs/info/doulahelp-test
      - name: Start the development application
        if: ${{ inputs.use_dev_server }}
        run:
          npm run dev -- --mode test & npx wait-on
          http://localhost:3000/humanservices/dmahs/info/doulahelp-test
      - name: Run cypress tests
        run: npm run ${{ inputs.cypress_run_command }}
      - name: Upload screenshots
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: cypress-screenshots-${{ inputs.name }} # inputs.name prevents artifact name conflicts if multiple tests fail and want to upload screenshots
          path: cypress/screenshots
