on:
  pull_request:

jobs:
  add-amplify-comment:
    # if: contains(github.head_ref, 'amplify')
    runs-on: ubuntu-latest
    steps:
      # - name: Get linked issues
      #   run: |
      #   echo "LINKED_ISSUES=$(gh api graphql -F owner='newjersey' -F repo='doula-medicaid' -F pr=PRNUMBER -f query=' \
      #   query ($owner: String!, $repo: String!, $pr: Int!) { \
      #     repository(owner: $owner, name: $repo) { \
      #       pullRequest(number: $pr) { \
      #         closingIssuesReferences(first: 100) { \
      #           nodes { \
      #             number \
      #           } \
      #         } \
      #       } \
      #     } \
      #   }'  --jq '.data.repository.pullRequest.closingIssuesReferences.nodes[].number)'" >> $GITHUB_ENV

      - name: Comment issue with amplify link
        run: gh issue comment 351 --body "Hi from GitHub CLI" --repo newjersey/doula-pm
        env:
          GH_TOKEN: ${{ secrets.DOULA_PM_ISSUE_COMMENT_TOKEN }}
        # with:
        #   github-token: ${{ secrets.DOULA_PM_ISSUE_COMMENT_TOKEN }}

        # body: 'App is being deployed to https://${{ github.head_ref }}.${{ secrets.AMPLIFY_APP_ID }}.amplifyapp.com/humanservices/dmahs/info/doulahelp. See the build at https://us-east-1.console.aws.amazon.com/amplify/apps/${{ secrets.AMPLIFY_APP_ID }}/branches/${{ github.head_ref }}/deployments'
