name: deploy-staging

on:
  push:
    branches:
      - "staging"

# Required to connect to AWS https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/
permissions:
  id-token: write
  contents: read

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  typecheck:
    uses: ./.github/workflows/typecheck.yml

  prettier:
    uses: ./.github/workflows/prettier.yml

  unit-tests:
    uses: ./.github/workflows/unit_tests.yml

  end-to-end-test:
    uses: ./.github/workflows/end_to_end_test.yml

  deploy-staging:
    needs: [lint, typecheck, prettier, unit-tests, end-to-end-test]
    uses: ./.github/workflows/_deploy.yml
    secrets:
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID_DEV }}
