name: deploy-staging-to-production

on: workflow_dispatch

permissions:
  contents: write

jobs:
  deploy-staging-to-production:
    uses: ./.github/workflows/_merge_branch.yml
    with:
      from_branch: staging
      into_branch: production

  # By default, a push by github actions does not trigger downstream actions https://github.com/ad-m/github-push-action/issues/32
  # So, the push does not automatically trigger production deploy
  deploy-prod:
    uses: ./.github/workflows/deploy_prod.yml
