name: deploy-main-to-staging

on: workflow_dispatch

permissions:
  contents: write

jobs:
  deploy-main-to-staging:
    uses: ./.github/workflows/_merge_branch.yml
    with:
      from_branch: main
      into_branch: staging

  # By default, a push by github actions does not trigger downstream actions https://github.com/ad-m/github-push-action/issues/32
  # So, the push does not automatically trigger staging deploy
  deploy-staging:
    uses: ./.github/workflows/deploy_staging.yml
