name: end-to-end-tests

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  workflow_call:

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - name: Build the application
        run: NODE_ENV=test npm run build
      - name: Start the application
        run:
          NODE_ENV=test npm start & npx wait-on
          http://localhost:3000/humanservices/dmahs/info/doulahelp
      - name: Run cypress tests
        run: npm run cypress:run
