name: end-to-end-tests-production-flags

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  workflow_call:

jobs:
  end-to-end-tests-production-flags:
    runs-on: ubuntu-latest
    steps:
      - name: Just a placeholder
        run:
          echo "This still exists at a stub because it is a required test on the repo, and only tech
          ops has permissions to remove it as required. We have submitted a request to remove it
          from being required, and will clean this up when that change has been made."
