name: end-to-end-tests-production-flags

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  workflow_call:

jobs:
  end-to-end-tests-production-flags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
  # This doesn't actually do anything, currently refactoring
  # These names are hardcoded to something that only tech ops has permissions on
