name: end-to-end-tests

on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"
  workflow_call:

jobs:
  end-to-end-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm ci
      - name: Build the application
        run: npm run build
      - name: Start the application
        run: npm start & npx wait-on http://localhost:3000
      - name: Run cypress tests
        run: npm run cypress:run
