name: merge-main-into-staging

on: workflow_dispatch

permissions:
  contents: write

jobs:
  merge-main-into-staging:
    uses: ./.github/workflows/_merge_branch.yml
    with:
      from_branch: main
      into_branch: staging
