name: merge-main-into-demo

on:
  workflow_dispatch:
  schedule:
    - cron: "0 14 * * 1" # Every Monday at 9am EST/10am EDT. Github actions run on UTC and as of writing [lacks timezone config](https://github.com/orgs/community/discussions/13454).

permissions:
  contents: write

jobs:
  merge-main-into-demo:
    uses: ./.github/workflows/_merge_branch.yml
    with:
      from_branch: main
      into_branch: demo
