name: merge-staging-into-production

on: workflow_dispatch

permissions:
  contents: write

jobs:
  merge-staging-into-production:
    uses: ./.github/workflows/_merge_branch.yml
    with:
      from_branch: staging
      into_branch: production
