name: test s3

on:
  pull_request:
    branches:
      - "main"
  workflow_call:
    secrets:
      aws_account_id:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.aws_account_id }}:role/GitHubAction-Doula
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
          mask-aws-account-id: true

      - name: Copy environment file
        run: aws s3 cp s3://doula-assistant-${{ secrets.aws_account_id }}/configuration/.env .env
